// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDRcN3Xy2Ot8bj1PRDnLo5pxK9Zu1awPI',
    appId: '1:963895541892:web:2cfd9b731f289e89bfc2d1',
    messagingSenderId: '963895541892',
    projectId: 'test-e92c3',
    authDomain: 'test-e92c3.firebaseapp.com',
    storageBucket: 'test-e92c3.appspot.com',
    measurementId: 'G-RB79Z6BJS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF-JKR5RaEULl45oehI0foqRsrzpJCgZU',
    appId: '1:963895541892:android:2f46aecdf807d9a4bfc2d1',
    messagingSenderId: '963895541892',
    projectId: 'test-e92c3',
    storageBucket: 'test-e92c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuJWIp46pmnPvUzho_dviHfR2PCr0ezQw',
    appId: '1:963895541892:ios:18ba65121b763051bfc2d1',
    messagingSenderId: '963895541892',
    projectId: 'test-e92c3',
    storageBucket: 'test-e92c3.appspot.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuJWIp46pmnPvUzho_dviHfR2PCr0ezQw',
    appId: '1:963895541892:ios:24166d0c893801cebfc2d1',
    messagingSenderId: '963895541892',
    projectId: 'test-e92c3',
    storageBucket: 'test-e92c3.appspot.com',
    iosBundleId: 'com.example.movieApp.RunnerTests',
  );
}
